const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('screencap', {
  getCaptureSources: () => ipcRenderer.invoke('get-capture-sources'),
  saveRecording: (buf, name) => ipcRenderer.invoke('save-recording', buf, name),
  saveScreenshot: (dataUrl) => ipcRenderer.invoke('save-screenshot', dataUrl),
  linkStart: () => ipcRenderer.invoke('link-start'),
  linkInfo: () => ipcRenderer.invoke('link-info'),
  onLinkStatus: (cb) => ipcRenderer.on('link-status', (e, s) => cb(s)),
  finalizeRecording: (buf, h264) => ipcRenderer.invoke('finalize-recording', buf, h264),
  libraryList: () => ipcRenderer.invoke('library-list'),
  libraryOpen: (p) => ipcRenderer.invoke('library-open', p),
  libraryOpenFolder: () => ipcRenderer.invoke('library-open-folder'),
  libraryDelete: (p) => ipcRenderer.invoke('library-delete', p),
  streamStart: (url, key, bitrateK, direct, micDevice, fx, audio) =>
    ipcRenderer.invoke('stream-start', url, key, bitrateK, direct, micDevice, fx, audio),
  streamChunk: (chunk) => ipcRenderer.send('stream-chunk', chunk),
  streamStop: () => ipcRenderer.invoke('stream-stop'),
  onStreamEnded: (cb) => ipcRenderer.on('stream-ended', (e, code, reason) => cb(code, reason)),
  onStreamHealth: (cb) => ipcRenderer.on('stream-health', (e, h) => cb(h)),
  onStreamRestarting: (cb) => ipcRenderer.on('stream-restarting', (e, n, reason, delay) => cb(n, reason, delay)),
  onStreamResume: (cb) => ipcRenderer.on('stream-resume', () => cb()),
  voiceFxAssets: () => ipcRenderer.invoke('voicefx-assets'),
  sessionActive: (on) => ipcRenderer.send('session-active', on),
  openExternal: (url) => ipcRenderer.invoke('open-external', url),
  listAudioApps: () => ipcRenderer.invoke('list-audio-apps'),
  listWindows: () => ipcRenderer.invoke('list-windows'),
  listCameras: () => ipcRenderer.invoke('list-cameras'),
  setSysGains: (gainsDb) => ipcRenderer.send('set-sys-gains', gainsDb),
  nativeRecordStart: (micDevice, fx, audio) => ipcRenderer.invoke('native-record-start', micDevice, fx, audio),
  nativeRecordStop: () => ipcRenderer.invoke('native-record-stop'),
  onNativeRecordFailed: (cb) => ipcRenderer.on('native-record-failed', () => cb()),
  yt: {
    status: () => ipcRenderer.invoke('yt-status'),
    setCredentials: (id, secret) => ipcRenderer.invoke('yt-set-credentials', id, secret),
    signIn: () => ipcRenderer.invoke('yt-sign-in'),
    signOut: () => ipcRenderer.invoke('yt-sign-out'),
    listBroadcasts: () => ipcRenderer.invoke('yt-list-broadcasts'),
    createBroadcast: (opts) => ipcRenderer.invoke('yt-create-broadcast', opts),
    prepareStream: (broadcastId) => ipcRenderer.invoke('yt-prepare-stream', broadcastId),
    prepareLive: (opts) => ipcRenderer.invoke('yt-prepare-live', opts),
    streamHealth: (streamId) => ipcRenderer.invoke('yt-stream-health', streamId),
    broadcastStatus: (broadcastId) => ipcRenderer.invoke('yt-broadcast-status', broadcastId),
    transition: (broadcastId, status) => ipcRenderer.invoke('yt-transition', broadcastId, status),
    setThumbnail: (broadcastId, filePath) => ipcRenderer.invoke('yt-set-thumbnail', broadcastId, filePath),
    chatStart: (liveChatId) => ipcRenderer.send('yt-chat-start', liveChatId),
    chatStop: () => ipcRenderer.send('yt-chat-stop'),
    chatSend: (liveChatId, text) => ipcRenderer.invoke('yt-chat-send', liveChatId, text),
    chatDelete: (messageId) => ipcRenderer.invoke('yt-chat-delete', messageId),
    chatBan: (liveChatId, channelId, seconds) => ipcRenderer.invoke('yt-chat-ban', liveChatId, channelId, seconds),
    chatAddMod: (liveChatId, channelId) => ipcRenderer.invoke('yt-chat-add-mod', liveChatId, channelId),
    onChatMessages: (cb) => ipcRenderer.on('yt-chat-messages', (e, msgs) => cb(msgs)),
  },
});
